### ISSUE TITLE
*Datatable* - _ Horizontal Scrollbar _ - Horizontal Scrollbar Missing After Edit

### ISSUE THREAD

**Issue by bromanowski** [alexed1/LightningFlowComponents#890] opened 2021-09-01 17:09 UTC
### Steps to reproduce

1. Go to a table with enough columns to have horizontal scrolling
2. Click on a editable field and change the value
3. Do not click save or cancel buttons
4. Scroll bar is gone

### Expected behavior
Horizontal scrollbar is still present and usable when edits have been made to datatable

### Actual behavior
Horizontal scrollbar disappears when an edit is made to the table

### Screenshots
![image](https://user-images.githubusercontent.com/3028526/131714149-df62c10b-181f-46f9-a5cd-a3e4ff5d2b90.png)

![image](https://user-images.githubusercontent.com/3028526/131714093-24dad603-c2a1-43d7-b1c6-645e052c8bfb.png)

**Comment by ericrsmith35** [comment] 2021-09-03 02:22
@JerrycsPoon Could something in the CSS be causing this?

**Comment by JerrycsPoon** [comment] 2021-09-03 11:22
Could be CSS or classes removed incorrectly on the datatable. I can have a look in a few days

**Comment by JerrycsPoon** [comment] 2021-09-05 08:59
This is an interesting one, as this is standard behaviour of lightning-datatable. Steps to reproduce:

1. head to https://developer.salesforce.com/docs/component-library/bundle/lightning-datatable/example 
2. click on inline edit under the 'example' dropdown
3. remove from the html file the 'suppress-bottom-bar'
4. Manually increase the width of columns
5. The horizontal scroll should appear
6. Edit any cell, and the save/edit footer will cover the horizontal bar

![image](https://user-images.githubusercontent.com/17759884/132121304-05f883c7-a18d-4416-a85e-7193d6b5e890.png)
![image](https://user-images.githubusercontent.com/17759884/132121307-c79a4e5a-ec90-47dd-ad3f-8c1d98ffdaa4.png)

**Comment by JerrycsPoon** [comment] 2021-09-05 09:11
I've bundled the fix on pull request: https://github.com/alexed1/LightningFlowComponents/pull/884

Note: the fix will increase the table's height while the footer is present. This is because now the footer's position is relative, which will be below the actual table. Previous it appears directly at the bottom of the table, covering the horizontal scroll

**Without fix:**
![image](https://user-images.githubusercontent.com/17759884/132121651-a10de65d-e893-47e3-b89f-f74830539a43.png)

**With fix:**
![image](https://user-images.githubusercontent.com/17759884/132121668-6dc3f1a4-268d-4c67-a25e-ac398318288b.png)

**Comment by ericrsmith35** [comment] 2021-09-05 19:03
This will be released in Winter '22 with version 3.3.3

**Closed by ericrsmith35** 2021-09-05 19:03 UTC
Labels: component:Datatable
