### ISSUE TITLE
*Datatable v4 (4.0.7)* - Single Record Display

### ISSUE THREAD

**Issue by nate-imagine** [alexed1/LightningFlowComponents#1163] opened 2022-07-07 16:27 UTC
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

### Steps to reproduce

1. Get Records for Datatable
2. Collection should only have one record found

### Expected behaviour
When only a single record exists, the row should still appear with either a checkbox or a radio button

### Actual behaviour

- The entire row is blank; user can still 'Select All' and datatable works as expected
- When multiple records exist, datatable works as expected and all rows appear correctly

### Screenshots

Only one record found:
<img width="501" alt="image" src="https://user-images.githubusercontent.com/107001136/177823508-f147fa8d-50ad-419c-8a45-4f02348c47b4.png">
<img width="489" alt="image" src="https://user-images.githubusercontent.com/107001136/177823600-d23acdb3-0b69-445a-9064-e0f9dc81605a.png">

Multiple records found:
<img width="485" alt="image" src="https://user-images.githubusercontent.com/107001136/177823663-99222fce-1f43-4df9-bb92-e79761687167.png">

### Debug Logs
If applicable, please insert debug logs here
<details>
<summary>Debug Log Information</summary>

```
Paste the output of the logs here.
```
</details>

**Comment by ericrsmith35** [comment] 2022-07-08 17:49
@nate-imagine Can you please share exactly how your record collection is being created and how you have configured the dfatatable?  I am unable to reproduce this behavior.

**Comment by nate-imagine** [comment] 2022-07-08 19:06
@ericrsmith35 here is a recording I did of the front end as well as how the flow is constructed. Please let me know if this helps. I was having some trouble with my scratch org, so apologies if it's a little jumpy.

Thanks!

https://user-images.githubusercontent.com/107001136/178055118-1f7670cb-684d-4a34-986f-2172e0f136f8.mp4

**Comment by ericrsmith35** [comment] 2022-07-08 23:39
Is it possible for me to get access to that org so I can try and
troubleshoot directly?

**Comment by nate-imagine** [comment] 2022-07-09 00:58
Yeah, no problem. Just invited you via your gmail, including the ticket number in your username/email. lmk if you didn't receive.

**Comment by ericrsmith35** [comment] 2022-07-09 15:38
The single row display issue has been resolved in v4.0.8.  It was caused by the Virtual Rendering option added in v4.0.6.

https://login.salesforce.com/packaging/installPackage.apexp?p0=04t5G000003rV0LQAU

**Closed by ericrsmith35** 2022-07-09 15:38 UTC
Labels: component:Datatable
