### ISSUE TITLE
SendBetterEmail - CPE - Cleared fields don't get nullified

### ISSUE THREAD

**Issue by marcbourlon** [alexed1/LightningFlowComponents#702] opened 2021-04-23 19:58 UTC
### Steps to reproduce

1. In a Flow, add the SendBetterEmail action, populate it as you wish, as long as you set a Template Name
2. Save the flow, use it, etc.
3. If you decide to clear the Template Name field, the Apex code crashes, because what it receives it not a null, as one would expect, but an empty string

### Expected behaviour
When a field is cleared in the configuration panel of the flow custom actions, the value is null

### Actual behaviour
Value is empty string

### Debug Logs
<details>
<summary>Debug Log Information</summary>
20:16:15.260 (322802579)|STATEMENT_EXECUTE|[379]
20:16:15.260 (322804782)|STATEMENT_EXECUTE|[380]
20:16:15.260 (322832040)|METHOD_ENTRY|[380]|01p3X00000HKexm|SendBetterEmailUtil.getTemplateIDFromName(String, String, Map<String,List<EmailTemplate>>, String)
20:16:15.260 (322864305)|VARIABLE_SCOPE_BEGIN|[166]|templateName|String|false|false
20:16:15.260 (322885015)|VARIABLE_ASSIGNMENT|[166]|templateName|""
20:16:15.260 (322892412)|VARIABLE_SCOPE_BEGIN|[166]|templateLanguage|String|false|false
20:16:15.260 (322904653)|VARIABLE_ASSIGNMENT|[166]|templateLanguage|null
20:16:15.260 (322914044)|VARIABLE_SCOPE_BEGIN|[166]|mapTemplateNameByEmailTemplates|Map<String,List<EmailTemplate>>|true|false
20:16:15.260 (322931045)|VARIABLE_ASSIGNMENT|[166]|mapTemplateNameByEmailTemplates|{}|0x4d25ebf6
20:16:15.260 (322941586)|VARIABLE_SCOPE_BEGIN|[166]|localKey|String|false|false
20:16:15.260 (322956074)|VARIABLE_ASSIGNMENT|[166]|localKey|"en_US"
20:16:15.260 (322971446)|HEAP_ALLOCATE|[172]|Bytes:5
20:16:15.260 (322983107)|STATEMENT_EXECUTE|[171]
20:16:15.260 (322985193)|STATEMENT_EXECUTE|[172]
20:16:15.260 (322988234)|VARIABLE_SCOPE_BEGIN|[172]|retTemplateID|String|false|false
20:16:15.260 (323002140)|VARIABLE_ASSIGNMENT|[172]|retTemplateID|null
20:16:15.260 (323009465)|STATEMENT_EXECUTE|[173]
20:16:15.260 (323013491)|VARIABLE_SCOPE_BEGIN|[173]|blankTemplate|String|false|false
20:16:15.260 (323026884)|VARIABLE_ASSIGNMENT|[173]|blankTemplate|null
20:16:15.260 (323073109)|STATEMENT_EXECUTE|[174]
20:16:15.260 (323075325)|STATEMENT_EXECUTE|[209]
20:16:15.260 (323082835)|METHOD_EXIT|[380]|01p3X00000HKexm|SendBetterEmailUtil.getTemplateIDFromName(String, String, Map<String,List<EmailTemplate>>, String)
20:16:15.260 (323095078)|VARIABLE_ASSIGNMENT|[380]|templateID|null
20:16:15.260 (323102024)|STATEMENT_EXECUTE|[386]
20:16:15.260 (323104089)|STATEMENT_EXECUTE|[387]
20:16:15.260 (323108145)|HEAP_ALLOCATE|[388]|Bytes:37
20:16:15.260 (323115665)|HEAP_ALLOCATE|[390]|Bytes:87
20:16:15.260 (323127523)|HEAP_ALLOCATE|[388]|Bytes:124
20:16:15.260 (323151226)|VARIABLE_ASSIGNMENT|[387]|this.errors|"Could not find email (104 more) ..."|0x33880547
20:16:15.260 (323162636)|STATEMENT_EXECUTE|[392]
20:16:15.260 (323172489)|VARIABLE_ASSIGNMENT|[392]|this.templateUsed|null|0x33880547
20:16:15.260 (323185109)|STATEMENT_EXECUTE|[395]
20:16:15.260 (323188975)|STATEMENT_EXECUTE|[403]
20:16:15.260 (323192378)|STATEMENT_EXECUTE|[412]
20:16:15.260 (323194299)|STATEMENT_EXECUTE|[420]
20:16:15.260 (323198066)|VARIABLE_SCOPE_BEGIN|[420]|completed|Boolean|false|false
20:16:15.260 (323212260)|HEAP_ALLOCATE|[420]|Bytes:5
20:16:15.260 (323220672)|VARIABLE_ASSIGNMENT|[420]|completed|true
20:16:15.260 (323227163)|STATEMENT_EXECUTE|[421]
20:16:15.260 (323229820)|VARIABLE_SCOPE_BEGIN|[421]|error|String|false|false
20:16:15.260 (323243133)|VARIABLE_ASSIGNMENT|[421]|error|null
20:16:15.260 (323250484)|STATEMENT_EXECUTE|[422]
20:16:15.260 (323253869)|STATEMENT_EXECUTE|[423]
20:16:15.260 (323365822)|HEAP_ALLOCATE|[423]|Bytes:16
20:16:15.260 (323518685)|FATAL_ERROR|System.StringException: Invalid id: 

Class.SendBetterEmail.SendEmail: line 423, column 1
20:16:15.260 (323538407)|FATAL_ERROR|System.StringException: Invalid id: 
</details>

**Comment by jdpond** [comment] 2021-06-11 15:36
This is a known problem that has had much discussion - and no resolution.  How to specify null versus how to specify "".  In flow, this is done by using {!$GlobalConstant.EmptyString} and assuming null otherwise.  HOWEVER, the CPE interface does not support returned null (as does the JSONParser which will return a value of "" unless you specify null - when it will return "null", which is EXACTLY what you don't want).  Let's resolve this and prolly need to get @alexed1 involved to assist us with modifying the CPE Interface software (Unless it's already been updated)

**Comment by marcbourlon** [comment] 2021-06-11 18:57
Thanks Jack.
What about a tiny change in your code that considers an empty string for the recipientId to be the same as null?
For this specific case, that would help!

Best regards,

**Comment by jdpond** [comment] 2021-06-11 19:47
What if you WANT to return an empty string?  That's the issue.
We ran across this with checkbox too.
The use case is "default".  Often Default is assigned when the value is null.  To explicitly state "I have set this to empty, so please don't reassign default after I set it to empty" when empty (initialized), null (not-initialized, set to default) and value supplied.

**Comment by marcbourlon** [comment] 2021-06-11 20:53
Jack, in the situation that bothers me, the issue is that the recipientId is sent as an empty string, while your code tests it against null. You cannot do anything with an empty Id anyway, which is why the action crashes.
I think there are tow issues here:
the CPE issue, tricky to solve
the crash of SendBetterEmail due to this bug, which is an easy one to solve (if recipientId is null or == '', instead of just if is null)

**Comment by jdpond** [comment] 2021-06-11 20:58
Ahhh, got it - thanks.  Let me look at it.

**Comment by jdpond** [comment] 2021-06-11 21:09
@marcbourlon Which parameter are you using to pass in recipientId, templateTargetObjectId?

**Closed** 2021-06-19 21:10 UTC
Labels: component:SendBetterEmail, pri:Medium

**Comment by AccelLeap** [comment] 2022-06-06 13:51
@jdpond Hi Jack, When we send email and there are multiple recipients the sendEmail method fails because of any invalid email address present in the list for eg: abc@test.com, test@test.com. Because in case of invalid email id atLeastOneSent in line 610 will be false and it will throw exception which is correct. But the issue is it fails to send email to any of the recipients and it fails for all. Did someone report this earlier or your thoughts on this?

Thanks & Regards,
Aakash

**Comment by AccelLeap** [comment] 2022-06-06 13:53
@jdpond Hi Jack,

How do we make changes to the apex class if we want to make any modification to your code?

**Comment by jdpond** [comment] 2022-06-06 14:06
The simple answer is "DON'T USE INVALID ADDRESSES".  The complex answer would have to be what to do if you do use invalid addresses.

Please check below to see if I got this right.

Are you suggesting we add code to determine and eliminate invalid addresses in SendBetterEmail then attempt resends and notify the admin that invalid sends were attempted in bad flows?  If so, how would you be notified:
1. Which emails were sent
2. Which emails had invalid addresses.
The problem is the [Message](https://developer.salesforce.com/docs/atlas.en-us.apexref.meta/apexref/apex_namespace_Messaging.htm) Namespace has defined methods which are used in SendBetterEmail which is a facilitator to simplify and allow more complex (and sometimes avoid limits) of the email capabilities, including multi-language. . .  These methods do not provide what looks like this recommendation?

**Comment by AccelLeap** [comment] 2022-06-06 14:11
> @jdpond Hi Jack,
> 
> How do we make changes to the apex class if we want to make any modification to your code?

@jdpond Thanks for the swift response. How do we do this?

**Comment by jdpond** [comment] 2022-06-06 14:13
Unless I got this wrong, making the change as recommended would fail in the sends without notifying the Admin the send failed.  Is this something recommended?

**Comment by jdpond** [comment] 2022-06-06 14:22
Part 2 needs to address:
1.  Do you want to create a private version of this?  If so, just copy the code from GitHub and modify it instead of using package.
2. If you want to update the code as part of the SendBetterEmail package maintained by UnofficialSF, we should add you to the team and the proposal would be a new Issue which would be reviewed and assessed by the team.
3. While we often do so and encourage such, the recommendation would also facilitate the use of SF as a Black Hatter tool unless we remediate using a security enhancement of some sort - not fully convinced the approach is 100% desireable.
