### ISSUE TITLE
Issue with 3 lookup fields on the same Flow Screen

### ISSUE THREAD

**Issue by kensation** [alexed1/LightningFlowComponents#26] opened 2018-05-25 20:27 UTC
I have 3 lookup fields on a Flow screen. One that is an independent field (Work Type) and then the other two are Account and then Contacts (related contacts).  As long as I fill out the fields in order, I don't have any issues, but if I go back to the work order lookup (which is question #1 on my screen), it will clear out my related contact lookup field and say "no records found!"

Can there be 3 of these lightning components on the same flow screen?

**Comment by alexed1** [comment] 2018-06-03 01:44
That problem usually means that an event fired by one component is getting handled by a subscriber from another similar component. The solution to this is generally to make sure that parents pass a unique id to children and then the children include that id in the payload of events they fire.   @ericrsmith35 @datapharmer if possible can you investigate this?

**Comment by kensation** [comment] 2018-06-04 16:39
I have tried putting Parent, Child, or not specifying any value in the "parent or child" attribute, but it's still not working correctly.

**Comment by ericrsmith35** [comment] 2018-06-05 20:21
@alexed1 Can you point me to an example of where events are identified with unique ids?

**Comment by alexed1** [comment] 2018-06-05 20:54
I'm not seeing it in the DynamicQuestion code...I think I might have tried it and then taken it out. I might have taken it out when I switched from Application Events to Component Events. The notifier event from the Dynamic Question child is a component event, so other Dynamic Question components won't see it. But I see that our Lookup is using Application events. So the path of least resistance may be to change to Component events. If you can't because you need a broader dissemination of events, then you need to load each event with some string unique to this instance of the Lookup. That could be the name, as I believe it's impossible to create two components on one screen with the same name. So Id is probably unnecessary. Simply modify your handler logic to check and see if the name in the payload of the incoming event matches the name of the component. That will filter out all but the appropriate events.

**Comment by ericrsmith35** [comment] 2018-06-08 01:20
The issue was caused by the Parent or Child parameter defaulting to Parent.  I have updated the code to allow that parameter to be blank for lookups that should not affect any other lookups on the same screen.  Only one Parent is supported per screen.  I will create push requests for the changes.

**Comment by alexed1** [comment] 2018-06-12 05:47
fixed in the version published tonight.

**Closed by alexed1** 2018-06-12 05:47 UTC
