### ISSUE TITLE
Pre-selected rows not working with SObject using Custom Property Editor

### ISSUE THREAD

**Issue by othious** [alexed1/LightningFlowComponents#735] opened 2021-05-21 15:53 UTC
This is an amazing component and I'm upgrading to the latest version in order to take advantage of some of your latest improvements, but I ran into an issue.  I'm trying to use the Datatable component version 3.2.1 to show a list of Contacts with some of the rows pre-selected.  I was able to do this with DatatableV2 prior to the Custom Property Editor, but this latest version of the component doesn't seem to pre-select anything.

### Steps to reproduce
1. Create flow with a Get Records action to get a list of Contacts for a specific Account
2. Add a Screen with the latest version of the Datatable component (3.2.1) and configure it to use the list of contacts for #1 as the data source for both display and which records that should be already selected.
3. Debug the flow and notice that none of the records are pre-selected.

### Expected behavior
All of the records should be pre-selected.

### Actual behavior
No records are pre-selected.

### Screenshots
![image](https://user-images.githubusercontent.com/2530929/119164189-c6630f80-ba21-11eb-8af9-10db1ecf20a9.png)
![image](https://user-images.githubusercontent.com/2530929/119164400-01654300-ba22-11eb-9d4a-43742a5cc6fc.png)

**Comment by ericrsmith35** [comment] 2021-05-21 21:02
Thanks for pointing this out.  I will look into the root cause.

**Comment by ericrsmith35** [comment] 2021-06-04 11:49
This will be corrected in the next release.

**Comment by ericrsmith35** [comment] 2021-06-11 16:42
This is fixed in v3.2.2
https://unofficialsf.com/datatable-latest-release-notes-v3-2-2/

**Closed by ericrsmith35** 2021-06-11 16:42 UTC
Labels: component:Datatable, type:bug
