### ISSUE TITLE
This page has an error. You might just need to refresh it. [Error during LWC component connect phase: [Invalid attempt to set a new value for property not_suppressNameFieldLink of [object:vm Datatable (24)] that does not has a setter decorated with @api.]] Failing descriptor: {markup://flowruntime:flowRuntimeV2}

### ISSUE THREAD

**Issue by david-bingham** [alexed1/LightningFlowComponents#682] opened 2021-04-09 16:29 UTC
Steps to reproduce:

 1. Create a new screenflow
 2. Drag a new Screen element onto the page
 3. Add Datatable lwc to screen
 4. Select any standard or custom object
 5. Open the Column Wizard
 6. select "pick" or "type" (doesn't matter)
 7. click "next"
 8. select any number of fields
 9. click "next"
 
Expected Outcome: 
I should see a table with sample records. 

Observed outcome:
I receive this error: 
`This page has an error. You might just need to refresh it. [Error during LWC component connect phase: [Invalid attempt to set a new value for property not_suppressNameFieldLink of [object:vm Datatable (24)] that does not has a setter decorated with @api.]] Failing descriptor: {markup://flowruntime:flowRuntimeV2}`

NOTES: 
I have uninstalled and reinstalled datatable and all of its depenendencies.
I have cleared my browser cache
No changes have been made in SF since last night. It was working fine.

**Comment by david-bingham** [comment] 2021-04-09 17:18
The plot thickens:

I installed FlowActionBasePack and FlowScreenBasePack in a brand new dev org, and received an "Internal Error has occured" error while trying to reproduce.

**Comment by ericrsmith35** [comment] 2021-04-11 13:14
I am not able to reproduce this behavior.

- I created a brand new Dev Org
- I installed FlowActionsBasePack v2.16
- I installed FlowScreenComponentsBasePack v2.2.0
- I installed Datatable v3.0.10
- I created a new Screen Flow
- I dragged "Datatable" onto the screen
- I selected the Account object 
- I selected "Configure Columns" and selected some fields
- The table and sample records appeared as expected

**Comment by ericrsmith35** [comment] 2021-05-21 13:32
@david-bingham Does your org have any special settings related to the myDomain or other url customization?

**Comment by ericrsmith35** [comment] 2021-05-21 13:57
@david-bingham I will fix this in the next release.  In the meantime you can comment out this line in datatable.js. (Appears at line 360 in the current release)

`this.not_suppressNameFieldLink = false;`

**Comment by ericrsmith35** [comment] 2021-06-11 16:48
This has been fixed in the current release.
https://unofficialsf.com/datatable-latest-release-notes-v3-2-2/

**Closed by ericrsmith35** 2021-06-11 16:48 UTC
Labels: component:Datatable
