### ISSUE TITLE
Error when trying to set default value

### ISSUE THREAD

**Issue by solo-1234** [alexed1/LightningFlowComponents#474] opened 2020-09-01 18:00 UTC
Hi! I'm trying to set a default value for a lookupfsc. I followed these instructions https://github.com/alexed1/LightningFlowComponents/issues/175 but something seems wrong.

I set it up prefilling Default Value with the record's name, and O1_Output Value with the record's id, but when I load a page with the flow embedded, I get an error toast message that says Cannot set property 'value' of null.

I can X the toast message an then the flow works, but it's not going to work for my users... is there something to do to fix that? Otherwise I'll have to skip the default value but that would be a shame.

Thank you!

@ericrsmith35 @alexed1

**Comment by ericrsmith35** [comment] 2020-09-02 18:55
I just tested this with a default value and was not able to reproduce your issue.

![Image 6](https://user-images.githubusercontent.com/24724447/92024553-5514ec80-ed2c-11ea-9028-77e20f7f7537.png)

**Comment by solo-1234** [comment] 2020-09-02 19:55
Thanks! Did you try embedding the flow on a lightning page? That's the only place where I saw the error.

**Comment by ericrsmith35** [comment] 2020-09-03 13:33
Yes, I also trying the test flow on a Lightning Record page without being
able to reproduce the error.

**Comment by adwhite75** [comment] 2020-12-28 18:41
Closing until more repro steps are provided

**Closed by adwhite75** 2020-12-28 18:41 UTC
