### ISSUE TITLE
OpenURL fails to call in a Spring '23 sandbox

### ISSUE THREAD

**Issue by bottomlinebrokers** [alexed1/LightningFlowComponents#1319] opened 2023-01-08 22:34 UTC
I use the OpenURL Flow Action (v1.0, https://unofficialsf.com/new-ways-to-open-web-pages-from-flow/) throughout our org as the final element in certain logic branches of screen flows.

Sometimes the url is simply a standard SF record, other times it calls Conga Composer (ex: /servlet/servlet.Integration?lid=00b37000000EboF&eid={!recordId}&ic=1), and sometimes it calls APEX (ex: /apex/blInformationPackage?id={!recordId}&draft=true).  The component has been very stable, and I have leveraged it extensively (and with great success) in screen flows throughout our org.

However, on Friday evening 1/6, our sandboxes updated to Spring '23.  I went to do some unrelated cleanup work in a sandbox today (expected a quiet Sunday morning) to discover that across all use cases, OpenURL fails to call in the flows.  I receive FlowApplication error emails with the message --

   Error Occurred: Timeout occurred 120 seconds after invoking "c:OpenURL".

The messages have various Salesforce Error IDs, but here is a sampling: 
778427592-111953 (69144822)
1437170426-124904 (69144822)
1437170426-130781 (69144822)

This is a major issue for our organization, as (like I mentioned above), OpenURL has made it into many of our screen flows.  Glad I found this in a sandbox early, but now it needs to get fixed ASAP.  Please advise on how I can help support a fix (data, screenshare, etc.); this borders on emergency for us.

Thank you!

Mark

**Comment by AndyHaas** [comment] 2023-01-09 00:22
@bottomlinebrokers 
What is the exact URL that you are using? I installed it in a Spring '23 ORG and had no issues.

**Comment by bottomlinebrokers** [comment] 2023-01-09 00:42
Andy,

It is already installed in my PROD org...it's been installed for awhile.  I'm not suggesting it won't install, I am stating it is no longer working.

Please clarify your request.

Mark
________________________________

**Comment by AndyHaas** [comment] 2023-01-09 01:11
Mark,
I have installed the OpenURL component in a Spring '23 org and gave the component a Replace for the mode and HTTPS://google.com for the URL. I then ran the flow, and everything worked within the Spring '23 org. 

What is the URL and Mode you have set up that is producing the error you are getting?

**Comment by bottomlinebrokers** [comment] 2023-01-09 01:26
All of our urls are internal.  Here are 4 samples:

/apex/blInformationPackage?id={!recordId}&draft=true   (replace)
/apex/blEmailBlastPreview?id={!recordId}  (replace)


/servlet/servlet.Integration?lid=00b37000000EboF&eid={!recordId}&ic=1 (replace)
/servlet/servlet.Integration?lid=00b37000000EbpX&eid={!recordId}&ic=1 (replace)

Note that these all work in PROD flows; the flow properly replaces the recordId.  Additionally, if I take any of these URLs and add the proper sandbox prefix (https://blbrokers--mpieter.sandbox.lightning.force.com/), in each test I've run, the complete URLs work fine.  It is the handoff that seems to be the issue.

Mark

P.S. Note that replace in the only mode that I've ever been able to get a openURL to work in.  I would LOVE newTab to work....that would be VERY helpful for my team, if that's possible.
________________________________

**Comment by AndyHaas** [comment] 2023-01-09 01:28
Mark,
Thank you for the URL; are these done via an Action, or where are these flows within your Org?

**Comment by bottomlinebrokers** [comment] 2023-01-09 01:30
In our org, we use OpenURL almost exclusively as final element of screen flows.

I'm happy to do this via screenshare if you're investigating.  Just email me a link.

Mark
***@***.***
________________________________

**Comment by AndyHaas** [comment] 2023-01-09 01:49
Mark,
Thanks for the information. 
I have created a simple flow that gathers case information and creates a case and passes that id to the open URL and the newTab functionality, which is default if you don't specify a mode, is working.

URL I am using:
https://reactivebeta.lightning.force.com/{!recCase.Id}

Mode not filled in

<img width="465" alt="Screenshot 2023-01-08 at 19 49 37" src="https://user-images.githubusercontent.com/22582720/211230040-28280ddb-e90f-4857-b6af-4c29eb7d732b.png">
<img width="588" alt="Screenshot 2023-01-08 at 19 49 31" src="https://user-images.githubusercontent.com/22582720/211230041-998d57f4-bc4c-4b41-a76b-6ec2fda86c66.png">

**Comment by bottomlinebrokers** [comment] 2023-01-09 01:52
The newTab functionality is my secondary concern at this time, the current replace functionality is where my emergency lies. 🙂

How can I assist troubleshooting?
________________________________

**Comment by bottomlinebrokers** [comment] 2023-01-09 02:11
Andy,

Good thoughts.  However:

1 - I tried multiple URLs from the flows prior to posting the issue to GitHub, all respond immediately and as expected (in under 10 seconds worst case), so that is not the issue.  The timeout is a side effect that OpenURL hangs.  The root cause is not a governor issue.

2 - I just (now) tried substituting one of the custom links with a standard link (https://www.arstechnica.com), and no luck.  Same hang, same timeout.

3 - As food for thought, I just used these screenflows on Friday morning in this sandbox wihtout issue, and today, no luck.  No changes over the weekend (I am the only user of this sandbox) except for upgrade to Spring '23 on Fri night.  These screen flows are long standing and very heavily used by my team (many times per hour) in PROD; I would have many objecting Agents if it weren't functioning before now for even 10 minutes. 🙂

Please, what can we do to troubleshoot?

Mark

________________________________

**Comment by AndyHaas** [comment] 2023-01-10 03:03
@bottomlinebrokers 
Try to disable LWS and see if that fixes the issue.

**Comment by bottomlinebrokers** [comment] 2023-01-10 03:05
How?  Where do I go to do that?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by AndyHaas** [comment] 2023-01-10 03:15
Check out the following document.
https://developer.salesforce.com/docs/component-library/documentation/en/lwc/lwc.security_lwsec_enable

**Comment by bottomlinebrokers** [comment] 2023-01-10 05:11
Andy,

Just got back to the computer.  That setting is already disabled in both PROD and MPIETER sandbox.

Next? 🙂

Mark


________________________________

**Comment by AndyHaas** [comment] 2023-01-10 12:59
Mark,
Are you able to provide a login into the sandbox with steps on how to reproduce this error? 

`andy.haas@milestoneconsulting.tech`

Thanks
Andy

**Comment by bottomlinebrokers** [comment] 2023-01-11 06:35
Andy,

Login created.
org login URL --  https://blbrokers--mpieter.sandbox.lightning.force.com
username --  ***@***.***
email -- ***@***.***


A great screen flow to see this issue is Action_Center_Listing.  The steps below will get you to the "Generate Draft Information Package" Action Element, which calls OpenURL.

You can get to this screen flow on any of our Listings (which is just the Opportunity object renamed).  Press the BLB Action Center, then select "Preview My Marketing", then select "Information Package".  It should work, but it does not.

Choose any of these records to test on: 0062f00000K0dVoAAJ, 0062f00000K0daKAAR, 0062f00000K0dXBAAZ, 0062f00000K0daxAAB, 0062f00000K0dWXAAZ

I'm up for a while, so let me know if you have problems getting org access.

Mark

P.S. I also tried to call OpenURL via this same screen flow in our UAT sandbox, which was also upgraded to Spring '23 on Friday.  No dice there either ... it fails.   All this still works in PROD. 🙂

________________________________

**Comment by AndyHaas** [comment] 2023-01-11 16:03
@bottomlinebrokers 
Here is my linked in
https://www.linkedin.com/in/ahaas2/

Send me a message there

**Comment by AndyHaas** [comment] 2023-01-11 22:47
Hey Mark,

You are all up and running. 

What was weird is that your version of OpenURL was different from on USF. I've commented out the old code and put in the correct code. I have deployed and tested it in your org, and everything is working as expected.

As per the new tab issue, this should also now be resolved, don't specify a mode, and a new tab will be open. This is a browser tab, not a Salesforce Tab. 

Thanks, Andy

**Comment by bottomlinebrokers** [comment] 2023-01-12 03:33
Very weird. While that's cool for a sandbox, it needs to be fixed across all orgs in a scalable way.

I can't uninstall OpenURL, too many flows rely upon it.  So that means I need to upgrade it.  Can you publish a new version (like a v1.01 or something) that can upgrade to the new code?

I'm happy to chat for a few and brainstorm as well.

Mark
c: (714)290-7145 (PST)
________________________________

**Comment by AndyHaas** [comment] 2023-01-12 18:30
Mark,
Since this is an Aura component, you can package this up within a Change Set and deploy it to the other sandboxes. No APEX tests or anything is needed. 

Let me know if you want me to create a change set in the org.

Thanks 
Andy

**Comment by bottomlinebrokers** [comment] 2023-01-13 17:54
Andy,

Good morning.  Can I get an ETA on the changeset in MPIETER sandbox?  It would be nice to push to UAT so I can do some testing.

I know it's a favor (and I appreciate the support), but I've never added an Aura component to a changeset before.

Thank you kindly!

Mark
________________________________

**Comment by AndyHaas** [comment] 2023-01-13 21:36
Mark, 
Here is the change set.
https://blbrokers--mpieter.sandbox.lightning.force.com/lightning/setup/OutboundChangeSet/page?address=%2Fchangemgmt%2FoutboundChangeSetDetailPage.apexp%3Fid%3D0A22f000000DOB9

Thanks 
Andy

**Comment by bottomlinebrokers** [comment] 2023-01-14 02:15
Well that was easy enough.  Thank you for your assistance.  I will keep you posted if I have any difficulties!

Mark
________________________________

**Comment by alexed1** [comment] 2023-01-14 20:39
@AndyHaas really nice of you to provide such detailed support!

So, is the conclusion here that @bottomlinebrokers was using a different set of code than the one currently available via package and in this repo? If so, I'd think we can close this...?

**Comment by bottomlinebrokers** [comment] 2023-01-14 23:10
Alex,

Before you close, consider that I installed this package directly from unofficialsf (https://unofficialsf.com/new-ways-to-open-web-pages-from-flow/).

I didn't edit the Aura component at all, so that means at some point, mine was the "official" installable code.  That seems to suggest that perhaps there are other orgs out there with my version, that perhaps won't work once Spring '23 goes live but haven't caught it yet?

Is it worth iterating the official installable to v1.1, so that any users in my spot can upgrade their code to the correct version without requiring developer help?

Food for thought before you close the ticket.

Mark



________________________________

**Comment by alexed1** [comment] 2023-01-15 23:07
ok, so Mark @bottomlinebrokers , you're saying that the current version of OpenURL, which is here (https://github.com/alexed1/LightningFlowComponents/tree/master/flow_action_components/OpenURL/force-app/main/default/aura/OpenURL), is creating problems. 

I would be happy to take a PR for an improved version. @AndyHaas , is that something you can provide here? I'm not yet clear on the code changes

**Comment by bottomlinebrokers** [comment] 2023-01-15 23:43
I wasn't the man who solved the problem, Andy Haas was, so I can't speak to the solution.  I just know that Andy said that the code in my Aura component doesn't match that which is currently online now, and since they're both supposedly "1.0" versions, maybe we should have a 1.1 so somebody can upgrade their Aura component (and self-solve their problem) before hitting up a community dev like I had to. 🙂

Thanks to both of you gentlemen for your community support.  I'm only of those who can make wonders happen with flow, but don't code ... so I rely on components like this to make my internal processes sing. 🙂

Mark

________________________________

**Comment by alexed1** [comment] 2023-01-30 01:22
Glad it worked out!

**Closed by alexed1** 2023-01-30 01:22 UTC
