### ISSUE TITLE
Lookup not required to match

### ISSUE THREAD

**Issue by AaronMHaag** [alexed1/LightningFlowComponents#176] opened 2019-08-01 18:40 UTC
When using the lookup in flow, I am able to type in a value to the field that is not in the lookup and move on the the next screen. 

For example, my lookup returns 3 options: A, B, and C and stores the choice to varService. I can enter D into the box and click next on the flow screen and varService gets set to D.

![image](https://user-images.githubusercontent.com/53579702/62318628-4180bd80-b46a-11e9-913f-cf67fb8db44f.png)
![image](https://user-images.githubusercontent.com/53579702/62318648-49406200-b46a-11e9-9ef4-e84ba3df4fa1.png)

**Comment by ericrsmith35** [comment] 2019-08-03 22:13
{!varService} should be in O1_Output Value in the Store Output Values section, not in the input section.  Try that and let me know what happens.

**Comment by adwhite75** [comment] 2020-12-28 18:40
Dupe of https://github.com/alexed1/LightningFlowComponents/issues/167

**Closed by adwhite75** 2020-12-28 18:40 UTC
