### ISSUE TITLE
QuickChoice - Section - Crashing when using Quickchoice in screen with Section Element

### ISSUE THREAD

**Issue by ImagineCRM-vcs** [alexed1/LightningFlowComponents#615] opened 2021-02-23 19:31 UTC
1. Create a Screen Flow
2. Create a Screen
3. Add a Section element
4. Add a Quick Choice
5. Set Picklist type and Picklist field data source, set the label and required
6. Debug

### Expected behavior
Not crash.

### Actual behavior
It crashes.

### Screenshots
![image](https://user-images.githubusercontent.com/78743530/108897156-ca7abf00-75e3-11eb-881b-973b44e4fc0d.png)

**Comment by alexed1** [comment] 2021-02-24 06:06
Yep, being worked on.

**Comment by adwhite75** [comment] 2021-02-24 20:13
Closing - dupe of #531

Duplicate of #531

**Closed by adwhite75** 2021-02-24 20:13 UTC
Labels: component:QuickChoice, pri:Medium, type:bug
