### ISSUE TITLE
Table edit issue Datatable Version #3.4.3

### ISSUE THREAD

**Issue by fefris** [alexed1/LightningFlowComponents#1050] opened 2022-02-16 01:23 UTC
Seeing an issue when editing table entries.

Edit the entry and the second you click out of the field it reverts to the old value HOWEVER if you then do an update as part of your flow it updates with the values you entered. So its a display bug where although you have edited the table cell it shows the old value.

In version 3.3.2 this did not happen and any entry in a table cell stayed as the entered value after the table save button was pressed.

Also note i have v 3.4.3 installed but the version number inside the component in the flow states 3.3.2 below the key field box.

Before Editing
![before edit](https://user-images.githubusercontent.com/30797036/154178332-d3becabd-5d2f-4eab-984b-8cc0e30b2821.jpg)

Mid Edit
![mid edit](https://user-images.githubusercontent.com/30797036/154178334-d8756b7b-2f71-46b9-8d84-d256658f0411.jpg)

After Save pressed

![after save pressed](https://user-images.githubusercontent.com/30797036/154178330-58788f8e-0791-46e8-a1bc-060381242ccd.jpg)

After Record update (and loop back to display collection)

![after record update](https://user-images.githubusercontent.com/30797036/154178325-d5ea7200-ab1c-43a6-afb1-9afc728ac677.jpg)

**Comment by sylvain-priser** [comment] 2022-02-22 18:47
Hi Eric, 

I noticed the same behavior as reported by fefris on version 3.4.5 with Checkbox and Text fields : when leaving the field with TAB or ENTER, or by clicking on another field, the field orginal value is restored. 

Picklist fields are OK and keep their local values (although only the last picklist field changed is up-to-date in the OutputEditedRows collection but I will raise a specific issue for this one).

The component has the "Hide Cancel/Save button" checkbox unchecked.

Here is a screen recording of the issue : [Video capture](https://www.dropbox.com/home?preview=20220222_193320.mp4)

**Comment by fefris** [comment] 2022-02-24 01:55
@ericrsmith35 same issue with 3.4.5 installed as per your link

**Comment by ericrsmith35** [comment] 2022-02-27 16:14
I am still not able to reproduce this issue

https://user-images.githubusercontent.com/24724447/155890246-e9c7ae0d-27ba-432d-a6d5-1caf8859a1b0.mp4

.

**Comment by sylvain-priser** [comment] 2022-02-28 00:34
Hi @ericrsmith35 ,

Thanks for your answer, I think I have found why it does not behave the same.

I just noticed that my Datatable component was embedded in a Section component. I removed the section and the Datatable works fine now ! Maybe it will need a new line in Troubleshooting & Restrictions...

By the way, this component is great, thank you for your work Eric & contributors !

FYI @fefris

**Comment by ericrsmith35** [comment] 2022-03-05 22:50
I have an open Case with Salesforce to find out why a Section component on a screen causes a change in how the Datatable behaves.

**Comment by RealEvanPonter** [comment] 2022-03-08 19:35
Hi @ericrsmith35 

I had v3.4.5 installed and ran into this issue where tabbing out of an edited cell in the datatable caused that cell to revert back to its previous value (in this scenario, back to null). I do have a section component on the same screen as my datatable, but the datatable is not inside of that section component.

I noticed we did not experience this issue on v3.3.2 (which was still installed in one of the connected sandboxes for this client), so I was able to patch this bug by reverting the "_tableData" attribute back to the "tableData" attribute in the datatable.js file. I can't pinpoint exactly _why_ this fixed the issue, but I wanted to pass along this information in case it helps with your investigation. Attached is my working version of datatable.js - a hybrid of v3.3.2 and v3.4.5

[datatable.txt](https://github.com/alexed1/LightningFlowComponents/files/8209107/datatable.txt)

**Comment by ericrsmith35** [comment] 2022-03-12 20:57
FYI @alexed1 - Can this extra refresh be avoided in the Datatable code or does something internally have to change around how Sections are handled?

@RealEvanPonter The switch to _tableData is in preparation to supporting a future flow enhancement where components can be reactive to other components on the same screen.  It looks like having a Section on a screen unnecessarily triggers a table refresh when inline edits are made to the table.

**Comment by kdoruibin** [comment] 2022-03-16 12:13
I'm on v3.4.5 and experiencing the same issue. It does seem to be somehow related to if there is a section in the screen or not. However, it doesn't matter if the datatable itself is in the section or not.

**Section exist in the screen, but datatable is outside of section**:
![2022-03-16_12-59-25 (1)](https://user-images.githubusercontent.com/50168096/158587195-575f71e5-517b-4c69-95cc-19c536e541b4.gif)

**All sections removed from the screen:**
![2022-03-16_13-04-41 (1)](https://user-images.githubusercontent.com/50168096/158587343-f6a7a6f6-df8f-4c2b-acf0-c0cb9d28b674.gif)

**Comment by ChewinChaz** [comment] 2022-08-08 18:15
I am experiencing this issue as well.  Like @kdoruibin said, it doesn't matter if the datatable is inside of the section, only if the section is on the same screen.  Are there any solutions available yet other than removing all sections from the flow screen?

**Comment by ChewinChaz** [comment] 2022-08-08 18:18
Also, this error randomly crops up when inline editing tables with a section on the screen.  It seems to be related somehow

![image](https://user-images.githubusercontent.com/43247068/183486193-a2d67036-69cd-4e13-ace0-a82566e27584.png)

**Comment by alexed1** [comment] 2022-08-09 03:56
@adwhite75 are you aware of any issues with custom components in sections?

@ericrsmith35 if you can set this up in an org with some credentials and a simple repro, we can try to get someone to investigate.

**Comment by adwhite75** [comment] 2022-08-09 13:53
Yes, but I believe @ericrsmith35  had fixed those issues already.

**Comment by ericrsmith35** [comment] 2022-08-09 14:23
@ChewinChaz & @kdoruibin What version of the component are you each running?  As @adwhite75 said, this should have been addressed in the more recent releases.

**Comment by ChewinChaz** [comment] 2022-08-09 20:36
@ericrsmith35 4.0.8

**Comment by ChewinChaz** [comment] 2022-08-19 19:01
Having a lot of users getting this [t[e].slice is not a function] error lately (see screenshot above).  Has anyone else reported this issue or figured out a way to resolve it?  Thanks @ericrsmith35!

**Comment by ericrsmith35** [comment] 2022-09-11 16:49
@ChewinChaz Do you still get this in 4.0.11?

**Comment by ChewinChaz** [comment] 2022-09-14 17:50
@ericrsmith35 I installed 4.0.11 on Monday and a user just sent me this screenshot 

![image](https://user-images.githubusercontent.com/43247068/190226395-22f3a015-1a21-4982-8082-e685bee8873d.png)

This is the first time I've seen this error on a screen that does not also use a section component so the two may not be related after all

**Comment by ericrsmith35** [comment] 2022-09-17 15:33
THis will be fixed in the next release (v4.0.12)

**Comment by ericrsmith35** [comment] 2022-09-17 15:44
It should only happen when one is editing a Date field and not hiding the Save/Cancel buttons

**Comment by ericrsmith35** [comment] 2022-10-11 07:40
Evan,

I have a case open with Salesforce to try and find out why Sections are
causing a change in behavior.

Eric Smith

**Comment by ericrsmith35** [comment] 2022-11-03 00:04
This has been resolved in version 4.0.12.  https://unofficialsf.com/datatable-lightning-web-component-for-flow-screens-2/#Installation

**Closed by ericrsmith35** 2022-11-03 00:04 UTC
Labels: component:Datatable
