### ISSUE TITLE
recordDetailFSC: View Mode Does Not Work

### ISSUE THREAD

**Issue by Ehsanyzd** [alexed1/LightningFlowComponents#312] opened 2020-04-02 04:06 UTC
When the mode is set to "view" nothing shows up. 
The console throws this error:
Uncaught (in promise) Error: Unknown public property "recordTypeId" of element <lightning-record-view-form>. This is likely a typo on the corresponding attribute "record-type-id".

**Root Cause:**
Line 26 of recordDetailFlowScreenComponent.html should be removed. 
**lightning-record-view-form** does not accept **record-type-id** variable.

**Comment by alexed1** [comment] 2020-04-19 05:16
@ericrsmith35  did you recent improvement fix this?

**Comment by ericrsmith35** [comment] 2020-04-19 13:35
I did not, nor was I able to reproduce the behavior described.

**Comment by alexed1** [comment] 2020-04-21 16:08
Yeah, can't repro this here either.

**Comment by Ehsanyzd** [comment] 2020-04-28 23:53
I can still reproduce even with version 1.5. Please note the error only happens in View mode. 
Here's what I am passing in:
![image](https://user-images.githubusercontent.com/32374672/80548227-4c23a100-896f-11ea-83ac-769af8690f8a.png)

When I place the flow in a Lightning Record Page, I get this error on page load:
![image](https://user-images.githubusercontent.com/32374672/80548296-783f2200-896f-11ea-8db0-ca17bc84da8c.png)

Based on documentation below, `<lightning-record-view-form>` does not have a record-type-id attribute. 
https://developer.salesforce.com/docs/component-library/bundle/lightning-record-view-form/specification

After removing record-type-id from `<lightning-record-view-form>` I no longer get the error and view mode works fine:
![image](https://user-images.githubusercontent.com/32374672/80548572-1a5f0a00-8970-11ea-974a-9e683ab78a39.png)

**Comment by ericrsmith35** [comment] 2020-04-29 14:18
I was still not able to reproduce this but here is a fix that removes that
line from the view form.

4/29/20 -   Eric Smith -    Version 1.6
                            Removed record-type-id={recordTypeId} from
lightning-record-view-form
Package Links
(Unmanaged)
https://login.salesforce.com/packaging/installPackage.apexp?p0=04t1K0000033LSb
https://test.salesforce.com/packaging/installPackage.apexp?p0=04t1K0000033LSb

**Comment by ericrsmith35** [comment] 2020-04-29 14:24
Fixed in Pull Request #346

**Closed by ericrsmith35** 2020-04-29 14:24 UTC
